apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviator-dashboard
  labels:
    app: aviator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aviator
  template:
    metadata:
      labels:
        app: aviator
        azure.workload.identity/use: "true"
        deploy-timestamp: "20260212-2210" # Forces K8s to see a change
    spec:
      serviceAccountName: aviator-service-account
      containers:
      - name: aviator-container
        image: aviatoracr.azurecr.io/aviator-app:v9
        imagePullPolicy: Always # Ensures it tries to pull fresh
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_CLIENT_ID
          value: "58737ab5-dd13-4381-b28e-82d46e297800"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: aviator-service
spec:
  type: LoadBalancer
  selector:
    app: aviator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
