#deplyment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviator-dashboard
  labels:
    app: aviator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aviator
  template:
    metadata:
      labels:
        app: aviator
    spec:
      containers:
      - name: dashboard
        image: aviatoracr.azurecr.io/aviator-app:v1
        ports:
        - containerPort: 5000
        # This environment variable tells the Python app which identity to use
        env:
        - name: AZURE_CLIENT_ID
          value: "a58e6bd1-f10e-4cd6-bd86-9aa8f641e5a3" # Extracted from your Entra Admin ID
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: aviator-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: aviator